// Mirror the repo-level `assets/` and `resume/` folders into `public/` and emit
// a manifest of what's present. Runs on predev/prebuild. Keeping this a copy
// (not a symlink) avoids Turbopack's "symlink escapes filesystem root" panic
// and keeps runtime bundle code free of any `fs` access.
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, "..");
const publicDir = resolve(projectRoot, "public");
const manifestFile = resolve(projectRoot, "src", "generated", "assets.ts");

/* ---------- 1. Media assets → public/assets ---------- */

const assetsSrc = resolve(projectRoot, "..", "assets");
const publicAssets = resolve(publicDir, "assets");
const MEDIA = new Set([
  "avif", "webp", "jpg", "jpeg", "png", "gif", "svg",
  "mp4", "webm", "mov", "m4v", "ogg",
]);

function walk(dir, base) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name.startsWith(".")) return [];
    const full = join(dir, entry.name);
    if (entry.isDirectory()) return walk(full, base);
    if (!MEDIA.has(extname(entry.name).slice(1).toLowerCase())) return [];
    return [relative(base, full).split("\\").join("/")];
  });
}

const files = walk(assetsSrc, assetsSrc).sort();
rmSync(publicAssets, { recursive: true, force: true });
for (const rel of files) {
  const to = join(publicAssets, rel);
  mkdirSync(dirname(to), { recursive: true });
  cpSync(join(assetsSrc, rel), to);
}

/* ---------- 2. Résumé → public/Rahul-Jakhar-CV.pdf ---------- */
// Drop any PDF into the repo-level `resume/` folder; the most recently
// modified one becomes the downloadable CV (served at a stable, tidy URL).

const resumeSrc = resolve(projectRoot, "..", "resume");
const RESUME_PUBLIC_NAME = "Rahul-Jakhar-CV.pdf";
const resumeDest = join(publicDir, RESUME_PUBLIC_NAME);

function newestPdf(dir) {
  if (!existsSync(dir)) return null;
  const pdfs = readdirSync(dir)
    .filter((f) => !f.startsWith(".") && extname(f).toLowerCase() === ".pdf")
    .map((f) => ({ f, m: statSync(join(dir, f)).mtimeMs }))
    .sort((a, b) => b.m - a.m);
  return pdfs.length ? pdfs[0].f : null;
}

const resumePdf = newestPdf(resumeSrc);
let resumeHref = null;
if (resumePdf) {
  cpSync(join(resumeSrc, resumePdf), resumeDest);
  resumeHref = `/${RESUME_PUBLIC_NAME}`;
} else {
  rmSync(resumeDest, { force: true });
}

/* ---------- 3. Manifest (imported by src/lib/assets.ts) ---------- */

mkdirSync(dirname(manifestFile), { recursive: true });
writeFileSync(
  manifestFile,
  `// AUTO-GENERATED by scripts/sync-assets.mjs — do not edit.\n` +
    `export const ASSET_FILES: readonly string[] = ${JSON.stringify(files, null, 2)};\n` +
    `export const RESUME_HREF: string | null = ${JSON.stringify(resumeHref)};\n`,
);

console.log(
  `[sync-assets] ${files.length} media file(s) → public/assets · résumé: ${resumePdf ?? "none"}`,
);
